const fileInputConvert = document.getElementById("convert-file");
fileInputConvert.addEventListener("change", function() {
    const btn = document.getElementById("convert-button")
    const file = this.files[0];
    if (!isFileValid(file)) {
        alert("Either file is not selected or not valid, please try another file.")
        this.value = ""
        btn.disabled = true;
        return;
    }
    btn.disabled = false;
})

const convertButton = document.getElementById("convert-button");
convertButton.addEventListener("click", async function() {
    let file = fileInputConvert.files[0];
    let text = await file.text();
    let name = file.name.split(".").slice(0, -1).join(".");
    let ext = file.name.split(".").pop();
    // Convert from srt to ass
    if (ext === "srt") {
        let subs = readSRTFile(text);
        let output = convertFromSRTToASS(subs);
        downloadTextFile(output, `${name}.ass`); 
    }
    // Convert from ass to srt
    else if (ext == "ass") {
        const {header, subs} = readASSFile(text);
        console.log(name);
        let output = convertFromASSToSRT(subs)
        downloadTextFile(output, `${name}.srt`);
    }
})

const ASS_HEADER = `[Script Info]
; Script generated by Aegisub 3.4.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,BIZ UDPGothic,45,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`

/**
 * Convert SRT subtitles to ASS format
 * @param {SubtitleSRT[]} subs - Array of SRT subtitles
 * @returns {string} Formatted ASS file content
 */
function convertFromSRTToASS(subs) {
    let ass_subs = [];
    for (const sub of subs) {
        let layer = 0;
        let startTime = sub.startTime.getASSTime();
        let endTime = sub.endTime.getASSTime();
        let style = "Default";
        let name = "";
        let marginL = 0;
        let marginR = 0;
        let marginV = 0;
        let effect = "";
        let text = sub.text;

        let ass_sub = new SubtitleASS(layer, startTime, endTime, style, name, marginL, marginR, marginV, effect, text);
        ass_subs.push(ass_sub);
    }

    return createASSFile(ASS_HEADER, ass_subs);
}

/**
 * Convert ASS subtitles to SRT format
 * @param {SubtitleASS[]} subs - Array of ASS subtitles
 * @returns {string} Formatted SRT file content
 */
function convertFromASSToSRT(subs) {
    let srt_subs = [];
    let i = 0;
    for (const sub of subs) {
        let index = i++;
        let startTime = sub.startTime.getSRTTime();
        let endTime = sub.endTime.getSRTTime();
        let text = sub.text;

        let srt_sub = new SubtitleSRT(index, startTime, endTime, text);
        srt_subs.push(srt_sub);
    }

    return createSRTFile(srt_subs);
}
